"""Gradio theme for the TactileGen UI."""

import gradio as gr

tactile_theme = gr.themes.Base(
    primary_hue="amber",
    secondary_hue="amber",
    neutral_hue="stone",
    text_size="lg",
    spacing_size="lg",
    radius_size="lg",
    font=[
        gr.themes.GoogleFont("Source Sans 3"),
        "ui-sans-serif",
        "system-ui",
        "sans-serif",
    ],
    font_mono=[
        gr.themes.GoogleFont("Source Code Pro"),
        "ui-monospace",
        "Consolas",
        "monospace",
    ],
).set(
    body_text_color_subdued="*neutral_500",
    background_fill_primary_dark="*neutral_900",
    background_fill_secondary_dark="*neutral_800",
    color_accent="*primary_600",
    link_text_color="*secondary_700",
    link_text_color_active="*secondary_700",
    link_text_color_hover="*secondary_800",
    link_text_color_visited="*secondary_700",
    link_text_color_visited_dark="*secondary_500",
    prose_header_text_weight="800",
    shadow_drop="0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
    shadow_drop_lg="0 0.25rem 0.75rem rgba(0, 0, 0, 0.1)",
    code_background_fill_dark="*neutral_700",
    block_background_fill="*background_fill_secondary",
    block_background_fill_dark="*background_fill_secondary",
    block_label_text_color="*body_text_color_subdued",
    block_label_text_color_dark="*body_text_color_subdued",
    block_shadow="*shadow_drop",
    block_shadow_dark="*shadow_drop",
    block_title_text_color="*body_text_color",
    block_title_text_color_dark="*body_text_color",
    section_header_text_weight="600",
    checkbox_background_color_dark="*background_fill_secondary",
    checkbox_border_color="*border_color_primary",
    checkbox_border_color_dark="*border_color_primary",
    checkbox_border_color_hover="*border_color_primary",
    checkbox_border_color_hover_dark="*border_color_primary",
    checkbox_label_shadow="*shadow_inset",
    input_background_fill="*neutral_200",
    input_placeholder_color="*body_text_color_subdued",
    input_placeholder_color_dark="*body_text_color_subdued",
    input_shadow="*shadow_inset",
    input_shadow_dark="*shadow_inset",
    table_border_color="*border_color_primary",
    table_border_color_dark="*border_color_primary",
    table_even_background_fill="*background_fill_primary",
    table_even_background_fill_dark="*background_fill_primary",
    table_odd_background_fill="*background_fill_secondary",
    table_odd_background_fill_dark="*background_fill_secondary",
    button_transform_hover="translateY(-1px)",
    button_transition="all 0.15s ease",
    button_large_radius="*radius_xxl",
    button_small_radius="*radius_xxl",
    button_small_text_weight="600",
    button_medium_radius="*radius_xxl",
    button_primary_background_fill="*neutral_800",
    button_primary_background_fill_dark="*neutral_200",
    button_primary_background_fill_hover="*neutral_700",
    button_primary_background_fill_hover_dark="*neutral_300",
    button_primary_border_color="*neutral_600",
    button_primary_border_color_dark="*neutral_400",
    button_primary_border_color_hover="*button_primary_border_color",
    button_primary_border_color_hover_dark="*button_primary_border_color",
    button_primary_text_color_dark="black",
    button_primary_shadow="*shadow_drop",
    button_primary_shadow_hover="*shadow_drop_lg",
    button_primary_shadow_dark="*shadow_drop",
    button_primary_shadow_hover_dark="*shadow_drop_lg",
    button_secondary_shadow_hover="*button_primary_shadow_hover",
    button_secondary_shadow_active="*button_primary_shadow_active",
    button_secondary_shadow_hover_dark="*button_primary_shadow_hover",
    button_secondary_shadow_active_dark="*button_primary_shadow_active",
    button_secondary_background_fill="*background_fill_primary",
    button_secondary_background_fill_dark="*background_fill_primary",
    button_secondary_background_fill_hover="*button_secondary_background_fill",
    button_secondary_background_fill_hover_dark="*button_secondary_background_fill",
    button_secondary_border_color="*neutral_400",
    button_secondary_border_color_dark="*neutral_500",
    button_secondary_border_color_hover="*body_text_color",
    button_secondary_border_color_hover_dark="*neutral_100",
    button_cancel_text_color="#991b1b",
    button_cancel_text_color_dark="#fecaca",
    button_cancel_text_color_hover="*button_cancel_text_color",
    button_cancel_text_color_hover_dark="*button_cancel_text_color",
    button_cancel_border_color_hover="*button_cancel_text_color",
    button_cancel_border_color_hover_dark="*button_cancel_text_color",
    button_border_width="1px",
    checkbox_label_background_fill="*input_background_fill",
    checkbox_label_background_fill_dark="*input_background_fill",
    checkbox_label_background_fill_hover="*neutral_300",
    checkbox_label_background_fill_hover_dark="*neutral_600",
)
